# Configs for setting up train/eval environments
setup:
  # Chooses whether to benchmark kernels
  benchmark_kernels: false
  # Uses only deterministic algorithms, impacts performance a lot
  use_deterministic_algorithms: false
  # Sets precision for float32 operations in CUDA matmul and cuDNN convolutions
  # 'highest' disables tf32
  # 'high' and 'medium' enable tf32
  tf32_level: high
  # Seed for computations
  seed: 42

  amp:
    # Enables/disables AMP
    enabled: true
    # Sets AMP data type
    dtype: [(obj), torch.bfloat16]

  # Enables/disables grad scaling
  grad_scaler: false

  distributed:
    # # Device used in current process. It is automatically computed
    # device: null
    # # Number of threads running in each process, already computed from cpu count and topology
    # num_threads: null
    # Torchrun already sets local and global ranks as environment variables
    # Number of process in the process group
    world_size: [(env), WORLD_SIZE, 1]
    # Number of processes locally
    local_world_size: [(env), LOCAL_WORLD_SIZE, 1]
    # Id of current process globally
    rank: [(env), RANK, 0]
    # Id of current process locally
    local_rank: [(env), LOCAL_RANK, 0]
    # Timeout for ddp process group
    timeout: 1800

train:
  # How many train steps to run in each epoch
  n_steps: 500000
  # For experiments
  n_real_steps: null
  # Display logs every n steps
  display_log_steps_interval: 10
  # Do evaluation and save results after every n steps
  val_steps_interval: 100

  # Power law fitting settings
  metric_power_law_fitting:
    # Whether to fit power laws at specified steps
    should_fit: true
    # At which steps to fit power laws to the metrics
    # -1 means last instant
    instants: [5000, 10000, 20000, 50000, 100000, 200000, 500000, -1]
    # Whether to only fit the power laws after the warmup steps
    skip_warmup_steps: true

  optimizer:
    # Number of warmup steps before going to cosine learning rate
    n_warmup_steps: 3000
    # Learning rate
    lr: 1e-4
    # AdamW betas
    betas: [0.999, 0.999]
    # AdamW weight decay
    weight_decay: 0.01
    # Fused kernels
    fused: true

  grad_clipping:
    # Types: null, 'abs', 'std'
    type: std
    # Moving average window size
    window_size: 100
    # Maximum gradient std allowed before clipping
    clip_std: 1.8 # when using std
    # Maximum gradient std allowed before skipping
    skip_std: 4.0 # when using std
    # # Maximum gradient norm allowed before clipping
    # clip_norm: 2.0 # when using abs
    # # Maximum gradient norm allowed before skipping
    # skip_norm: 5.0 # when using abs

  logger:
    project_name: VDST
    run_group_name: null
    run_name: vdst

  checkpoints:
    # Folder in which to save checkpoints
    path: results/checkpoints/
    # Whether to load only weights, should be false only for checkpoints from trusted sources
    weights_only: false
    # Save checkpoints after every n steps (forward/backward pass)
    checkpoint_steps_interval: 1000

  data:
    # Num workers per GPU
    num_workers: 4
    prefetch_factor: 16
    shuffle: true
    pin_memory: false
    train_batch_size: 4
    val_batch_size: 4

    n_sources: 2
    n_targets: 6
    output_dims: [256, 256]

    # Datasets
    datasets:
      wildrgbd:
        path: ./datasets/wildrgbd/
        # Type of dataset, can be either 'raw' (raw dataset), 'cones_unconstrained' (dataset was processed splitting into view cones but use it as if it was raw), 'cones_constrained' (dataset was processed splitting into view cones and constrain it to the cones)
        # Constrained views are when the targets are in between the sources to prevent forcing the model to hallucinate regions it has no information about
        dataset_type: cones_constrained

  loss:
    # image_mse, image_perceptual, depth_silog, depth_multiscale, depth_perceptual
    # weights: [3.0, 0.5, 1.0, 1.0, 0.4]
    weights: [2.0, 1.0, 1.0, 1.0, 1.0]
    # weights: [0.5, 1.0, 0.5, 1.0, 0.5]
    should_normalize_weights: true
    # Perceptual loss config
    perceptual:
      # Either 'constant' or 'falling_perceptual'
      scheduler: falling_perceptual
      image:
        # Either 'default', 'default_size_224', 'default_size_236', 'normalize' or 'standardize'
        transforms: default_size_224
        # Weights for each layer, either array or null for all ones
        weights: null
        # Either 'convnext', 'vgg', 'vgg2', 'vgg3'
        type: convnext
        # weights: [2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        # weights: [1.6, 1.0, 0.8, 0.7, 0.5, 0.5, 0.5, 0.5, 0.5)#, 0.2]
        # type: vgg
        # weights: [2.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        # type: vgg2
        # weights: [2.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        # type: vgg3
        # weights: [2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        # Either 'nearest' or 'default' (bilinear)
        interpolation: default
        # Either 'image', 'log_depth' or 'norm_log_depth'
        input_type: image
        # If true, compares the difference between the images with the average image (just an image with all values at exactly the mean)
        is_diff: false
      depth:
        transforms: default_size_224
        weights: null
        type: convnext
        interpolation: nearest
        input_type: norm_log_depth
        is_diff: true
        # Threshold for depth mask, can be either in 0-1 range, or < 0 or null to allow all values or 'mean_std' for mean + 1.0*std or 'mean_max' for 0.4*mean + 0.6*max
        mask_threshold: mean_std
    # SILog loss config
    silog:
      # How much to penalize absolute scale errors
      scale_lambda: 0.15

# Default model configuration
model:
  # Patch side length (the images will be broken into patches of size p x p)
  p: 8
  # Number of color channels in each frame
  C: 3
  # Ray embedding for sources pose encoder
  # Can be either 'plucker' (uses plucker ray embeddings), 'origin_direction' (uses raw camera origin and directions), 'origin_only' (uses only raw camera origin), 'direction_only' (uses only raw direction) or null (no ray embeddings)
  # 'origin_only', 'direction_only' or null only make sense if depth_input_type is 'spatial', otherwise the problem is underconstrained
  ray_embedding_source: plucker
  # Ray embedding for queries pose encoder
  # Can be either 'plucker' or 'origin_direction', otherwise the problem is underconstrained
  ray_embedding_query: plucker
  # How will depths be input into the model
  # Can be either 'depth' (inputs depths), 'spatial' (inputs global pixel positions in space) or null (no depth inputs, just uses source images)
  depth_input_type: depth # TODO implement 'spatial'
  # Whether the model also has input depth masks to know whether pixels are valid or not
  # This is ignored if depth_input_type is null
  has_input_depth_masks: false

  # Number of layers in transformer
  n_layers: 6
  # Dimension of all the vector representations used in the transformer models (dim for all vector inputs in transformers, not just the embedding vectors that will be the latent representations of scenes, idk why did i put such a confusing name but yeah)
  d_model: 768
  # Dimension of vector representations in the attention space of transformer block (normally chosen to be equal to d_model)
  d_attn: 768
  # Number of attention heads in both encoder and decoder (n_heads should divide d_attn)
  n_heads: 12
  # Expansion factor for mlp blocks after attention blocks in each transformer block (embeddings will be expanded to e_ff * d_model dimensions then contracted back to d_model dimensions)
  e_ff: 4
  qk_norm:
    # Enables QK-Norm
    enabled: true
    # Epsilon for QK-Norm computation
    eps: 1e-12
  # Operation used for attention, should be from xops.fmha
  attn_op: [(obj), xformers.ops.fmha.MemoryEfficientAttentionFlashAttentionOp]
  # Enable/disable layer norm in enc layers
  enc_layer_norm: false
  enc_residual_layer_norm: false
  # Enable/disable layer norm in dec layers
  dec_layer_norm: false
  dec_residual_layer_norm: false
  # Depth range (min, max)
  d_range: [0.01, 1000.0] # 1cm to 1km
  # Type of normalization for images and depths
  # Can be either 'standardize' (standardizes depths to to mean 0 std 1) 'min_max' (normalizes depth to min-max range) or null
  depth_normalization_type: null
  # Output used for image, can be either 'linear' or 'sigmoid'
  image_output_type: linear
  # Output used for normalized depth before denormalizing it, can be either 'linear' or 'sigmoid'
  # If depth_normalization_type is not 'min_max', this is ignored
  norm_depth_output_type: linear
  # Enable/disable activation checkpointing
  use_activation_checkpointing: true

  train:
    # Dropout rate
    dropout: 0.0
