overrides:
  model:
    has_input_depths: true
    has_input_depth_masks: true
    enc_layer_norm: false
    enc_residual_layer_norm: false
    dec_layer_norm: false
    dec_residual_layer_norm: false
    standardize_inputs: false
  train:
    val_steps_interval: 50
    n_steps: 500000

    loss:
      weights: [2.0,2.0,0.7,1.5,1.0]
      perceptual:
        scheduler: constant
    optimizer:
      lr: 1e-4 # For now the best was 1e-4
      n_warmup_steps: 3000

setup:
  out_path: results/experiments/
  total_experiment_steps: 30000

experiments:
  # spatial_pixel:
  #   VDST:
  #     train:
  #       optimizer:
  #         lr: 1e-4
  #   S-VDST: # Spatial VDST 
  #     train:
  #       optimizer:
  #         lr: 1e-4
  #   P-VDST: # Pixel VDST
  #     # Maybe add residual connection in tokens and use d_model=d_attn=d_input
  #     model:
  #       p: 1
  #       d_model: 16
  #       d_attn: 16
  #       n_heads: 1
  #       e_ff: 4
  #     train:
  #       data:
  #         output_dims: [64, 64]
  #         train_batch_size: 8
  #         val_batch_size: 8
  #   SP-VDST: # Spatial-Pixel VDST
  #     # Maybe add residual connection in tokens and use d_model=d_attn=d_input
  #     model:
  #       p: 1
  #       d_model: 16
  #       d_attn: 16
  #       n_heads: 1
  #       e_ff: 4
  #     train:
  #       data:
  #         output_dims: [64, 64]
  #         train_batch_size: 8
  #         val_batch_size: 8
  d mask:
    with d mask:
      model:
        has_input_depth_masks: true
    without d mask:
      model:
        has_input_depth_masks: false
  isolated losses:
    regular:
      loss:
        weights: [2.0,2.0,0.7,1.5,1.0]
    without i mse:
      loss:
        weights: [0.0,2.0,0.7,1.5,1.0]
    without i percep:
      loss:
        weights: [2.0,0.0,0.7,1.5,1.0]
    without d silog:
      loss:
        weights: [2.0,2.0,0.0,1.5,1.0]
    without d mscale grad:
      loss:
        weights: [2.0,2.0,0.7,0.0,1.0]
    without d percep:
      loss:
        weights: [2.0,2.0,0.7,0.0,1.0]
